In [218]:
# Import libraries
import numpy as np
import pandas as pd

In [219]:
df = pd.read_csv('./original.csv')

In [220]:
df['Volume_(BTC)'] = df['Volume_(BTC)'].fillna(0)
df['Volume_(Currency)'] = df['Volume_(Currency)'].fillna(0)


df.Timestamp = pd.to_datetime(df.Timestamp, unit='s')
df['Year'] = df['Timestamp'].dt.year

In [221]:
df = df[df.Year != 2011]
df = df[df.Year != 2012]
df = df[df.Year != 2013]
df.head()

,Timestamp,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price,Year
1053608,2014-01-01 00:00:00,732.00,732.00,732.00,732.00,4.599562,3366.879047,732.000000,2014
1053609,2014-01-01 00:01:00,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,2014
1053610,2014-01-01 00:02:00,732.01,732.75,729.01,729.01,1.138530,830.438062,729.394976,2014
1053611,2014-01-01 00:03:00,730.24,732.76,730.24,732.76,0.121000,88.596624,732.203507,2014
1053612,2014-01-01 00:04:00,732.76,734.00,732.76,734.00,52.120000,38251.836202,733.918576,2014

In [222]:
len(df['Volume_(BTC)'])

3803769

In [223]:
BTC_Volume = []
BTC_count = 0
BTC_element = 0
for BTC_volume in ((df['Volume_(BTC)'])):
    BTC_count += 1
    BTC_element += BTC_volume
    BTC_Volume.append(BTC_element)
    if BTC_count == 59:
        BTC_count = 0
        BTC_element = 0

CURRENCY_Volume = []
CURRENCY_count = 0
CURRENCY_element = 0
for CURRENCY_volume in ((df['Volume_(Currency)'])):
    CURRENCY_count += 1
    CURRENCY_element += CURRENCY_volume
    CURRENCY_Volume.append(CURRENCY_element)
    if CURRENCY_count == 59:
        CURRENCY_count = 0
        CURRENCY_element = 0

In [224]:
df= df.reset_index()
df.head()

,index,Timestamp,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price,Year
0,1053608,2014-01-01 00:00:00,732.00,732.00,732.00,732.00,4.599562,3366.879047,732.000000,2014
1,1053609,2014-01-01 00:01:00,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,2014
2,1053610,2014-01-01 00:02:00,732.01,732.75,729.01,729.01,1.138530,830.438062,729.394976,2014
3,1053611,2014-01-01 00:03:00,730.24,732.76,730.24,732.76,0.121000,88.596624,732.203507,2014
4,1053612,2014-01-01 00:04:00,732.76,734.00,732.76,734.00,52.120000,38251.836202,733.918576,2014

In [225]:
to_be_added1 = pd.DataFrame({'BTC_Volume':BTC_Volume})
df = pd.concat([df, to_be_added1], axis=1)
to_be_added2 = pd.DataFrame({'CURRENCY_Volume':CURRENCY_Volume})
df = pd.concat([df, to_be_added2], axis=1)
df.head(20)

,index,Timestamp,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price,Year,BTC_Volume,CURRENCY_Volume
0,1053608,2014-01-01 00:00:00,732.00,732.00,732.00,732.00,4.599562,3366.879047,732.000000,2014,4.599562,3366.879047
1,1053609,2014-01-01 00:01:00,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,2014,4.599562,3366.879047
2,1053610,2014-01-01 00:02:00,732.01,732.75,729.01,729.01,1.138530,830.438062,729.394976,2014,5.738092,4197.317109
3,1053611,2014-01-01 00:03:00,730.24,732.76,730.24,732.76,0.121000,88.596624,732.203507,2014,5.859092,4285.913733
4,1053612,2014-01-01 00:04:00,732.76,734.00,732.76,734.00,52.120000,38251.836202,733.918576,2014,57.979092,42537.749935
5,1053613,2014-01-01 00:05:00,733.70,734.00,730.51,734.00,2.710080,1984.290334,732.188752,2014,60.689172,44522.040269
6,1053614,2014-01-01 00:06:00,733.70,734.00,733.70,734.00,0.264000,193.766100,733.962500,2014,60.953172,44715.806369
7,1053615,2014-01-01 00:07:00,734.00,734.34,734.00,734.34,4.000000,2937.306432,734.326608,2014,64.953172,47653.112801
8,1053616,2014-01-01 00:08:00,732.19,733.70,730.33,733.70,13.010490,9508.721435,730.850370,2014,77.963662,57161.834235
9,1053617,2014-01-01 00:09:00,NaN,NaN,NaN,NaN,0.000000,0.000000,NaN,2014,77.963662,57161.834235
10,1053618,2014-01-01 00:10:00,733.70,733.70,733.70,733.70,0.003000,2.201100,733.700000,2014,77.966662,57164.035335
11,1053619,2014-01-01 00:11:00,733.71,733.71,733.70,733.70,2.881830,2114.398765,733.700033,2014,80.848492,59278.434100
12,1053620,2014-01-01 00:12:00,734.00,734.48,734.00,734.48,1.470000,1079.527131,734.372198,2014,82.318492,60357.961231
13,1053621,2014-01-01 00:13:00,734.36,734.50,734.36,734.50,3.122200,2293.188471,734.478403,2014,85.440692,62651.149702
14,1053622,2014-01-01 00:14:00,734.50,734.50,733.70,734.50,12.965575,9521.289692,734.351546,2014,98.406266,72172.439394
15,1053623,2014-01-01 00:15:00,734.50,735.00,734.50,735.00,1.897141,1393.522932,734.538339,2014,100.303408,73565.962326
16,1053624,2014-01-01 00:16:00,734.99,735.00,734.99,735.00,25.472449,18722.216931,734.998702,2014,125.775857,92288.179257
17,1053625,2014-01-01 00:17:00,735.00,735.00,735.00,735.00,1.056800,776.748000,735.000000,2014,126.832657,93064.927257
18,1053626,2014-01-01 00:18:00,732.19,735.00,732.19,735.00,5.050000,3710.972143,734.845969,2014,131.882657,96775.899399
19,1053627,2014-01-01 00:19:00,732.19,732.19,732.19,732.19,0.999700,731.970343,732.190000,2014,132.882357,97507.869742

In [226]:
df['Open'] = df['Open'].fillna(0)
df = df[df['Open'] != 0.000000]

In [227]:
df= df.reset_index()
df.head(20)

,level_0,index,Timestamp,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price,Year,BTC_Volume,CURRENCY_Volume
0,0,1053608,2014-01-01 00:00:00,732.00,732.00,732.00,732.00,4.599562,3366.879047,732.000000,2014,4.599562,3366.879047
1,2,1053610,2014-01-01 00:02:00,732.01,732.75,729.01,729.01,1.138530,830.438062,729.394976,2014,5.738092,4197.317109
2,3,1053611,2014-01-01 00:03:00,730.24,732.76,730.24,732.76,0.121000,88.596624,732.203507,2014,5.859092,4285.913733
3,4,1053612,2014-01-01 00:04:00,732.76,734.00,732.76,734.00,52.120000,38251.836202,733.918576,2014,57.979092,42537.749935
4,5,1053613,2014-01-01 00:05:00,733.70,734.00,730.51,734.00,2.710080,1984.290334,732.188752,2014,60.689172,44522.040269
5,6,1053614,2014-01-01 00:06:00,733.70,734.00,733.70,734.00,0.264000,193.766100,733.962500,2014,60.953172,44715.806369
6,7,1053615,2014-01-01 00:07:00,734.00,734.34,734.00,734.34,4.000000,2937.306432,734.326608,2014,64.953172,47653.112801
7,8,1053616,2014-01-01 00:08:00,732.19,733.70,730.33,733.70,13.010490,9508.721435,730.850370,2014,77.963662,57161.834235
8,10,1053618,2014-01-01 00:10:00,733.70,733.70,733.70,733.70,0.003000,2.201100,733.700000,2014,77.966662,57164.035335
9,11,1053619,2014-01-01 00:11:00,733.71,733.71,733.70,733.70,2.881830,2114.398765,733.700033,2014,80.848492,59278.434100
10,12,1053620,2014-01-01 00:12:00,734.00,734.48,734.00,734.48,1.470000,1079.527131,734.372198,2014,82.318492,60357.961231
11,13,1053621,2014-01-01 00:13:00,734.36,734.50,734.36,734.50,3.122200,2293.188471,734.478403,2014,85.440692,62651.149702
12,14,1053622,2014-01-01 00:14:00,734.50,734.50,733.70,734.50,12.965575,9521.289692,734.351546,2014,98.406266,72172.439394
13,15,1053623,2014-01-01 00:15:00,734.50,735.00,734.50,735.00,1.897141,1393.522932,734.538339,2014,100.303408,73565.962326
14,16,1053624,2014-01-01 00:16:00,734.99,735.00,734.99,735.00,25.472449,18722.216931,734.998702,2014,125.775857,92288.179257
15,17,1053625,2014-01-01 00:17:00,735.00,735.00,735.00,735.00,1.056800,776.748000,735.000000,2014,126.832657,93064.927257
16,18,1053626,2014-01-01 00:18:00,732.19,735.00,732.19,735.00,5.050000,3710.972143,734.845969,2014,131.882657,96775.899399
17,19,1053627,2014-01-01 00:19:00,732.19,732.19,732.19,732.19,0.999700,731.970343,732.190000,2014,132.882357,97507.869742
18,20,1053628,2014-01-01 00:20:00,732.19,735.48,732.07,735.12,0.191056,140.309389,734.388810,2014,133.073413,97648.179131
19,21,1053629,2014-01-01 00:21:00,735.48,735.49,731.81,735.49,1.192060,872.991280,732.338372,2014,134.265473,98521.170411

In [228]:
Opens = []
open_count = 0
open_element = 0
df['level_0']= df['level_0'].astype(int)

for opens in ((df['Open'])):
    if int(df.iat[open_count,0]%60)==0:
        open_element=opens 
    Opens.append(open_element)
    open_count += 1
to_be_added3 = pd.DataFrame({'Hourly_Open':Opens})
df = pd.concat([df, to_be_added3], axis=1)
df.head(62)

,level_0,index,Timestamp,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price,Year,BTC_Volume,CURRENCY_Volume,Hourly_Open
0,0,1053608,2014-01-01 00:00:00,732.00,732.00,732.00,732.00,4.599562,3366.879047,732.000000,2014,4.599562,3366.879047,732.00
1,2,1053610,2014-01-01 00:02:00,732.01,732.75,729.01,729.01,1.138530,830.438062,729.394976,2014,5.738092,4197.317109,732.00
2,3,1053611,2014-01-01 00:03:00,730.24,732.76,730.24,732.76,0.121000,88.596624,732.203507,2014,5.859092,4285.913733,732.00
3,4,1053612,2014-01-01 00:04:00,732.76,734.00,732.76,734.00,52.120000,38251.836202,733.918576,2014,57.979092,42537.749935,732.00
4,5,1053613,2014-01-01 00:05:00,733.70,734.00,730.51,734.00,2.710080,1984.290334,732.188752,2014,60.689172,44522.040269,732.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,68,1053676,2014-01-01 01:08:00,738.50,739.94,738.50,739.94,11.030000,8159.327159,739.739543,2014,27.557260,20383.724642,739.02
58,69,1053677,2014-01-01 01:09:00,738.11,738.11,737.70,737.70,1.100000,811.483181,737.711983,2014,28.657260,21195.207823,739.02
59,70,1053678,2014-01-01 01:10:00,737.70,737.70,737.65,737.65,8.772028,6470.710048,737.652664,2014,37.429289,27665.917872,739.02
60,71,1053679,2014-01-01 01:11:00,737.66,737.66,737.66,737.66,0.089000,65.651740,737.660000,2014,37.518289,27731.569612,739.02
61,73,1053681,2014-01-01 01:13:00,737.70,737.70,737.70,737.70,0.015359,11.330002,737.700000,2014,37.533647,27742.899614,739.02

In [229]:
Closes = []
close_count = 0
close_element = 0

for closes in ((df['Close'])):
    if int(df.iat[close_count,0]%60)==59:
        close_element=closes 
    Closes.append(close_element)
    close_count += 1
to_be_added4 = pd.DataFrame({'Hourly_Close':Closes})
df = pd.concat([df, to_be_added4], axis=1)
df.head(55)

,level_0,index,Timestamp,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price,Year,BTC_Volume,CURRENCY_Volume,Hourly_Open,Hourly_Close
0,0,1053608,2014-01-01 00:00:00,732.00,732.00,732.00,732.00,4.599562,3366.879047,732.000000,2014,4.599562,3366.879047,732.00,0.00
1,2,1053610,2014-01-01 00:02:00,732.01,732.75,729.01,729.01,1.138530,830.438062,729.394976,2014,5.738092,4197.317109,732.00,0.00
2,3,1053611,2014-01-01 00:03:00,730.24,732.76,730.24,732.76,0.121000,88.596624,732.203507,2014,5.859092,4285.913733,732.00,0.00
3,4,1053612,2014-01-01 00:04:00,732.76,734.00,732.76,734.00,52.120000,38251.836202,733.918576,2014,57.979092,42537.749935,732.00,0.00
4,5,1053613,2014-01-01 00:05:00,733.70,734.00,730.51,734.00,2.710080,1984.290334,732.188752,2014,60.689172,44522.040269,732.00,0.00
5,6,1053614,2014-01-01 00:06:00,733.70,734.00,733.70,734.00,0.264000,193.766100,733.962500,2014,60.953172,44715.806369,732.00,0.00
6,7,1053615,2014-01-01 00:07:00,734.00,734.34,734.00,734.34,4.000000,2937.306432,734.326608,2014,64.953172,47653.112801,732.00,0.00
7,8,1053616,2014-01-01 00:08:00,732.19,733.70,730.33,733.70,13.010490,9508.721435,730.850370,2014,77.963662,57161.834235,732.00,0.00
8,10,1053618,2014-01-01 00:10:00,733.70,733.70,733.70,733.70,0.003000,2.201100,733.700000,2014,77.966662,57164.035335,732.00,0.00
9,11,1053619,2014-01-01 00:11:00,733.71,733.71,733.70,733.70,2.881830,2114.398765,733.700033,2014,80.848492,59278.434100,732.00,0.00
10,12,1053620,2014-01-01 00:12:00,734.00,734.48,734.00,734.48,1.470000,1079.527131,734.372198,2014,82.318492,60357.961231,732.00,0.00
11,13,1053621,2014-01-01 00:13:00,734.36,734.50,734.36,734.50,3.122200,2293.188471,734.478403,2014,85.440692,62651.149702,732.00,0.00
12,14,1053622,2014-01-01 00:14:00,734.50,734.50,733.70,734.50,12.965575,9521.289692,734.351546,2014,98.406266,72172.439394,732.00,0.00
13,15,1053623,2014-01-01 00:15:00,734.50,735.00,734.50,735.00,1.897141,1393.522932,734.538339,2014,100.303408,73565.962326,732.00,0.00
14,16,1053624,2014-01-01 00:16:00,734.99,735.00,734.99,735.00,25.472449,18722.216931,734.998702,2014,125.775857,92288.179257,732.00,0.00
15,17,1053625,2014-01-01 00:17:00,735.00,735.00,735.00,735.00,1.056800,776.748000,735.000000,2014,126.832657,93064.927257,732.00,0.00
16,18,1053626,2014-01-01 00:18:00,732.19,735.00,732.19,735.00,5.050000,3710.972143,734.845969,2014,131.882657,96775.899399,732.00,0.00
17,19,1053627,2014-01-01 00:19:00,732.19,732.19,732.19,732.19,0.999700,731.970343,732.190000,2014,132.882357,97507.869742,732.00,0.00
18,20,1053628,2014-01-01 00:20:00,732.19,735.48,732.07,735.12,0.191056,140.309389,734.388810,2014,133.073413,97648.179131,732.00,0.00
19,21,1053629,2014-01-01 00:21:00,735.48,735.49,731.81,735.49,1.192060,872.991280,732.338372,2014,134.265473,98521.170411,732.00,0.00
20,23,1053631,2014-01-01 00:23:00,732.55,732.55,732.03,732.03,0.990000,724.746020,732.066687,2014,135.255473,99245.916431,732.00,0.00
21,24,1053632,2014-01-01 00:24:00,732.05,738.00,731.82,731.99,125.161012,92270.936643,737.217884,2014,260.416485,191516.853074,732.00,0.00
22,25,1053633,2014-01-01 00:25:00,738.10,738.25,738.10,738.25,4.220000,3115.309214,738.224932,2014,264.636485,194632.162288,732.00,0.00
23,27,1053635,2014-01-01 00:27:00,737.66,737.66,734.56,734.56,1.517070,1116.049982,735.661494,2014,266.153555,195748.212271,732.00,0.00
24,29,1053637,2014-01-01 00:29:00,734.81,734.81,734.81,734.81,0.026000,19.105060,734.810000,2014,266.179555,195767.317331,732.00,0.00
25,32,1053640,2014-01-01 00:32:00,734.81,734.81,734.81,734.81,0.024700,18.149961,734.810000,2014,266.204255,195785.467292,732.00,0.00
26,33,1053641,2014-01-01 00:33:00,737.66,738.23,737.66,738.23,2.600000,1919.062390,738.100919,2014,268.804255,197704.529682,732.00,0.00
27,34,1053642,2014-01-01 00:34:00,737.66,738.23,737.66,738.23,3.770000,2783.108229,738.224994,2014,272.574255,200487.637911,732.00,0.00
28,36,1053644,2014-01-01 00:36:00,735.51,738.23,735.51,738.23,3.122260,2304.806612,738.185317,2014,275.696515,202792.444523,732.00,0.00
29,37,1053645,2014-01-01 00:37:00,738.22,738.23,734.81,734.81,13.543910,9970.030348,736.126447,2014,289.240425,212762.474871,732.00,0.00
30,38,1053646,2014-01-01 00:38:00,737.75,738.23,737.75,738.23,1.200000,885.837539,738.197949,2014,290.440425,213648.312409,732.00,0.00
31,40,1053648,2014-01-01 00:40:00,737.66,737.91,737.66,737.91,2.155986,1590.915733,737.906173,2014,292.596412,215239.228143,732.00,0.00
32,41,1053649,2014-01-01 00:41:00,735.47,735.47,735.47,735.47,0.137917,101.433632,735.470000,2014,292.734328,215340.661775,732.00,0.00
33,42,1053650,2014-01-01 00:42:00,735.47,738.28,735.47,738.28,42.360000,31268.097592,738.151501,2014,335.094328,246608.759367,732.00,0.00
34,43,1053651,2014-01-01 00:43:00,738.28,738.28,735.47,735.47,7.290326,5382.288321,738.278104,2014,342.384655,251991.047688,732.00,0.00
35,44,1053652,2014-01-01 00:44:00,735.47,735.47,735.47,735.47,0.009325,6.858111,735.470000,2014,342.393980,251997.905798,732.00,0.00
36,45,1053653,2014-01-01 00:45:00,735.47,735.47,735.47,735.47,0.008719,6.412416,735.470000,2014,342.402698,252004.318214,732.00,0.00
37,46,1053654,2014-01-01 00:46:00,735.47,738.49,735.47,738.49,5.205402,3844.108227,738.484339,2014,347.608101,255848.426441,732.00,0.00
38,47,1053655,2014-01-01 00:47:00,738.31,738.49,734.47,734.47,1.013608,748.481617,738.432678,2014,348.621709,256596.908058,732.00,0.00
39,48,1053656,2014-01-01 00:48:00,735.47,738.20,734.50,738.20,3.824190,2820.748737,737.606886,2014,352.445899,259417.656795,732.00,0.00
40,49,1053657,2014-01-01 00:49:00,738.19,739.00,734.53,739.00,167.145990,123505.029950,738.905133,2014,519.591889,382922.686745,732.00,0.00
41,50,1053658,2014-01-01 00:50:00,739.00,739.00,734.81,739.00,27.580649,20381.887296,738.992303,2014,547.172538,403304.574041,732.00,0.00
42,51,1053659,2014-01-01 00:51:00,736.04,739.18,736.04,736.04,4.838370,3575.531972,738.995152,2014,552.010908,406880.106013,732.00,0.00
43,52,1053660,2014-01-01 00:52:00,736.13,736.13,736.04,736.04,0.040000,29.444570,736.114250,2014,552.050908,406909.550583,732.00,0.00
44,53,1053661,2014-01-01 00:53:00,738.98,739.27,736.04,737.64,5.831960,4311.129566,739.224817,2014,557.882868,411220.680149,732.00,0.00
45,54,1053662,2014-01-01 00:54:00,738.98,739.27,737.64,737.64,0.101088,74.651182,738.474044,2014,557.983957,411295.331331,732.00,0.00
46,55,1053663,2014-01-01 00:55:00,737.64,739.28,737.64,737.64,4.548020,3360.617897,738.918856,2014,562.531977,414655.949228,732.00,0.00
47,56,1053664,2014-01-01 00:56:00,737.64,739.28,737.64,739.28,1.020000,754.000000,739.215686,2014,563.551977,415409.949228,732.00,0.00
48,57,1053665,2014-01-01 00:57:00,738.11,738.11,737.64,737.64,0.084049,62.013488,737.824535,2014,563.636026,415471.962716,732.00,0.00
49,58,1053666,2014-01-01 00:58:00,738.11,739.90,737.64,737.70,11.422030,8443.702065,739.247057,2014,575.058056,423915.664781,732.00,0.00
50,59,1053667,2014-01-01 00:59:00,739.02,739.02,739.02,739.02,0.089524,66.159997,739.020000,2014,0.089524,66.159997,732.00,739.02
51,60,1053668,2014-01-01 01:00:00,739.02,739.97,739.02,739.97,14.949450,11059.256836,739.776837,2014,15.038974,11125.416833,739.02,739.02
52,62,1053670,2014-01-01 01:02:00,739.00,739.00,739.00,739.00,0.380000,280.820000,739.000000,2014,15.418974,11406.236833,739.02,739.02
53,64,1053672,2014-01-01 01:04:00,739.00,739.00,738.11,738.11,0.903966,667.230170,738.113905,2014,16.322940,12073.467003,739.02,739.02
54,65,1053673,2014-01-01 01:05:00,738.50,738.50,738.50,738.50,0.100000,73.850000,738.500000,2014,16.422940,12147.317003,739.02,739.02

In [230]:
Highs = []
high_count = 0
high_element = 0
for highs in ((df['High'])):
    if int(df.iat[high_count,0]%60)==0:
        high_element=highs
    if highs>high_element:
        high_element=highs
    Highs.append(high_element)
    high_count += 1
to_be_added5 = pd.DataFrame({'Hourly_High':Highs})
df = pd.concat([df, to_be_added5], axis=1)
df.head(55)

,level_0,index,Timestamp,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price,Year,BTC_Volume,CURRENCY_Volume,Hourly_Open,Hourly_Close,Hourly_High
0,0,1053608,2014-01-01 00:00:00,732.00,732.00,732.00,732.00,4.599562,3366.879047,732.000000,2014,4.599562,3366.879047,732.00,0.00,732.00
1,2,1053610,2014-01-01 00:02:00,732.01,732.75,729.01,729.01,1.138530,830.438062,729.394976,2014,5.738092,4197.317109,732.00,0.00,732.75
2,3,1053611,2014-01-01 00:03:00,730.24,732.76,730.24,732.76,0.121000,88.596624,732.203507,2014,5.859092,4285.913733,732.00,0.00,732.76
3,4,1053612,2014-01-01 00:04:00,732.76,734.00,732.76,734.00,52.120000,38251.836202,733.918576,2014,57.979092,42537.749935,732.00,0.00,734.00
4,5,1053613,2014-01-01 00:05:00,733.70,734.00,730.51,734.00,2.710080,1984.290334,732.188752,2014,60.689172,44522.040269,732.00,0.00,734.00
5,6,1053614,2014-01-01 00:06:00,733.70,734.00,733.70,734.00,0.264000,193.766100,733.962500,2014,60.953172,44715.806369,732.00,0.00,734.00
6,7,1053615,2014-01-01 00:07:00,734.00,734.34,734.00,734.34,4.000000,2937.306432,734.326608,2014,64.953172,47653.112801,732.00,0.00,734.34
7,8,1053616,2014-01-01 00:08:00,732.19,733.70,730.33,733.70,13.010490,9508.721435,730.850370,2014,77.963662,57161.834235,732.00,0.00,734.34
8,10,1053618,2014-01-01 00:10:00,733.70,733.70,733.70,733.70,0.003000,2.201100,733.700000,2014,77.966662,57164.035335,732.00,0.00,734.34
9,11,1053619,2014-01-01 00:11:00,733.71,733.71,733.70,733.70,2.881830,2114.398765,733.700033,2014,80.848492,59278.434100,732.00,0.00,734.34
10,12,1053620,2014-01-01 00:12:00,734.00,734.48,734.00,734.48,1.470000,1079.527131,734.372198,2014,82.318492,60357.961231,732.00,0.00,734.48
11,13,1053621,2014-01-01 00:13:00,734.36,734.50,734.36,734.50,3.122200,2293.188471,734.478403,2014,85.440692,62651.149702,732.00,0.00,734.50
12,14,1053622,2014-01-01 00:14:00,734.50,734.50,733.70,734.50,12.965575,9521.289692,734.351546,2014,98.406266,72172.439394,732.00,0.00,734.50
13,15,1053623,2014-01-01 00:15:00,734.50,735.00,734.50,735.00,1.897141,1393.522932,734.538339,2014,100.303408,73565.962326,732.00,0.00,735.00
14,16,1053624,2014-01-01 00:16:00,734.99,735.00,734.99,735.00,25.472449,18722.216931,734.998702,2014,125.775857,92288.179257,732.00,0.00,735.00
15,17,1053625,2014-01-01 00:17:00,735.00,735.00,735.00,735.00,1.056800,776.748000,735.000000,2014,126.832657,93064.927257,732.00,0.00,735.00
16,18,1053626,2014-01-01 00:18:00,732.19,735.00,732.19,735.00,5.050000,3710.972143,734.845969,2014,131.882657,96775.899399,732.00,0.00,735.00
17,19,1053627,2014-01-01 00:19:00,732.19,732.19,732.19,732.19,0.999700,731.970343,732.190000,2014,132.882357,97507.869742,732.00,0.00,735.00
18,20,1053628,2014-01-01 00:20:00,732.19,735.48,732.07,735.12,0.191056,140.309389,734.388810,2014,133.073413,97648.179131,732.00,0.00,735.48
19,21,1053629,2014-01-01 00:21:00,735.48,735.49,731.81,735.49,1.192060,872.991280,732.338372,2014,134.265473,98521.170411,732.00,0.00,735.49
20,23,1053631,2014-01-01 00:23:00,732.55,732.55,732.03,732.03,0.990000,724.746020,732.066687,2014,135.255473,99245.916431,732.00,0.00,735.49
21,24,1053632,2014-01-01 00:24:00,732.05,738.00,731.82,731.99,125.161012,92270.936643,737.217884,2014,260.416485,191516.853074,732.00,0.00,738.00
22,25,1053633,2014-01-01 00:25:00,738.10,738.25,738.10,738.25,4.220000,3115.309214,738.224932,2014,264.636485,194632.162288,732.00,0.00,738.25
23,27,1053635,2014-01-01 00:27:00,737.66,737.66,734.56,734.56,1.517070,1116.049982,735.661494,2014,266.153555,195748.212271,732.00,0.00,738.25
24,29,1053637,2014-01-01 00:29:00,734.81,734.81,734.81,734.81,0.026000,19.105060,734.810000,2014,266.179555,195767.317331,732.00,0.00,738.25
25,32,1053640,2014-01-01 00:32:00,734.81,734.81,734.81,734.81,0.024700,18.149961,734.810000,2014,266.204255,195785.467292,732.00,0.00,738.25
26,33,1053641,2014-01-01 00:33:00,737.66,738.23,737.66,738.23,2.600000,1919.062390,738.100919,2014,268.804255,197704.529682,732.00,0.00,738.25
27,34,1053642,2014-01-01 00:34:00,737.66,738.23,737.66,738.23,3.770000,2783.108229,738.224994,2014,272.574255,200487.637911,732.00,0.00,738.25
28,36,1053644,2014-01-01 00:36:00,735.51,738.23,735.51,738.23,3.122260,2304.806612,738.185317,2014,275.696515,202792.444523,732.00,0.00,738.25
29,37,1053645,2014-01-01 00:37:00,738.22,738.23,734.81,734.81,13.543910,9970.030348,736.126447,2014,289.240425,212762.474871,732.00,0.00,738.25
30,38,1053646,2014-01-01 00:38:00,737.75,738.23,737.75,738.23,1.200000,885.837539,738.197949,2014,290.440425,213648.312409,732.00,0.00,738.25
31,40,1053648,2014-01-01 00:40:00,737.66,737.91,737.66,737.91,2.155986,1590.915733,737.906173,2014,292.596412,215239.228143,732.00,0.00,738.25
32,41,1053649,2014-01-01 00:41:00,735.47,735.47,735.47,735.47,0.137917,101.433632,735.470000,2014,292.734328,215340.661775,732.00,0.00,738.25
33,42,1053650,2014-01-01 00:42:00,735.47,738.28,735.47,738.28,42.360000,31268.097592,738.151501,2014,335.094328,246608.759367,732.00,0.00,738.28
34,43,1053651,2014-01-01 00:43:00,738.28,738.28,735.47,735.47,7.290326,5382.288321,738.278104,2014,342.384655,251991.047688,732.00,0.00,738.28
35,44,1053652,2014-01-01 00:44:00,735.47,735.47,735.47,735.47,0.009325,6.858111,735.470000,2014,342.393980,251997.905798,732.00,0.00,738.28
36,45,1053653,2014-01-01 00:45:00,735.47,735.47,735.47,735.47,0.008719,6.412416,735.470000,2014,342.402698,252004.318214,732.00,0.00,738.28
37,46,1053654,2014-01-01 00:46:00,735.47,738.49,735.47,738.49,5.205402,3844.108227,738.484339,2014,347.608101,255848.426441,732.00,0.00,738.49
38,47,1053655,2014-01-01 00:47:00,738.31,738.49,734.47,734.47,1.013608,748.481617,738.432678,2014,348.621709,256596.908058,732.00,0.00,738.49
39,48,1053656,2014-01-01 00:48:00,735.47,738.20,734.50,738.20,3.824190,2820.748737,737.606886,2014,352.445899,259417.656795,732.00,0.00,738.49
40,49,1053657,2014-01-01 00:49:00,738.19,739.00,734.53,739.00,167.145990,123505.029950,738.905133,2014,519.591889,382922.686745,732.00,0.00,739.00
41,50,1053658,2014-01-01 00:50:00,739.00,739.00,734.81,739.00,27.580649,20381.887296,738.992303,2014,547.172538,403304.574041,732.00,0.00,739.00
42,51,1053659,2014-01-01 00:51:00,736.04,739.18,736.04,736.04,4.838370,3575.531972,738.995152,2014,552.010908,406880.106013,732.00,0.00,739.18
43,52,1053660,2014-01-01 00:52:00,736.13,736.13,736.04,736.04,0.040000,29.444570,736.114250,2014,552.050908,406909.550583,732.00,0.00,739.18
44,53,1053661,2014-01-01 00:53:00,738.98,739.27,736.04,737.64,5.831960,4311.129566,739.224817,2014,557.882868,411220.680149,732.00,0.00,739.27
45,54,1053662,2014-01-01 00:54:00,738.98,739.27,737.64,737.64,0.101088,74.651182,738.474044,2014,557.983957,411295.331331,732.00,0.00,739.27
46,55,1053663,2014-01-01 00:55:00,737.64,739.28,737.64,737.64,4.548020,3360.617897,738.918856,2014,562.531977,414655.949228,732.00,0.00,739.28
47,56,1053664,2014-01-01 00:56:00,737.64,739.28,737.64,739.28,1.020000,754.000000,739.215686,2014,563.551977,415409.949228,732.00,0.00,739.28
48,57,1053665,2014-01-01 00:57:00,738.11,738.11,737.64,737.64,0.084049,62.013488,737.824535,2014,563.636026,415471.962716,732.00,0.00,739.28
49,58,1053666,2014-01-01 00:58:00,738.11,739.90,737.64,737.70,11.422030,8443.702065,739.247057,2014,575.058056,423915.664781,732.00,0.00,739.90
50,59,1053667,2014-01-01 00:59:00,739.02,739.02,739.02,739.02,0.089524,66.159997,739.020000,2014,0.089524,66.159997,732.00,739.02,739.90
51,60,1053668,2014-01-01 01:00:00,739.02,739.97,739.02,739.97,14.949450,11059.256836,739.776837,2014,15.038974,11125.416833,739.02,739.02,739.97
52,62,1053670,2014-01-01 01:02:00,739.00,739.00,739.00,739.00,0.380000,280.820000,739.000000,2014,15.418974,11406.236833,739.02,739.02,739.97
53,64,1053672,2014-01-01 01:04:00,739.00,739.00,738.11,738.11,0.903966,667.230170,738.113905,2014,16.322940,12073.467003,739.02,739.02,739.97
54,65,1053673,2014-01-01 01:05:00,738.50,738.50,738.50,738.50,0.100000,73.850000,738.500000,2014,16.422940,12147.317003,739.02,739.02,739.97

In [231]:
Lows = []
low_count = 0
low_element = 0
for lows in ((df['Low'])):
    if int(df.iat[low_count,0]%60)==0:
        low_element=lows
    if lows<low_element:
        low_element=lows
    Lows.append(low_element)
    low_count += 1
to_be_added6 = pd.DataFrame({'Hourly_Low':Lows})
df = pd.concat([df, to_be_added6], axis=1)
df.head(55)

,level_0,index,Timestamp,Open,High,Low,Close,Volume_(BTC),Volume_(Currency),Weighted_Price,Year,BTC_Volume,CURRENCY_Volume,Hourly_Open,Hourly_Close,Hourly_High,Hourly_Low
0,0,1053608,2014-01-01 00:00:00,732.00,732.00,732.00,732.00,4.599562,3366.879047,732.000000,2014,4.599562,3366.879047,732.00,0.00,732.00,732.00
1,2,1053610,2014-01-01 00:02:00,732.01,732.75,729.01,729.01,1.138530,830.438062,729.394976,2014,5.738092,4197.317109,732.00,0.00,732.75,729.01
2,3,1053611,2014-01-01 00:03:00,730.24,732.76,730.24,732.76,0.121000,88.596624,732.203507,2014,5.859092,4285.913733,732.00,0.00,732.76,729.01
3,4,1053612,2014-01-01 00:04:00,732.76,734.00,732.76,734.00,52.120000,38251.836202,733.918576,2014,57.979092,42537.749935,732.00,0.00,734.00,729.01
4,5,1053613,2014-01-01 00:05:00,733.70,734.00,730.51,734.00,2.710080,1984.290334,732.188752,2014,60.689172,44522.040269,732.00,0.00,734.00,729.01
5,6,1053614,2014-01-01 00:06:00,733.70,734.00,733.70,734.00,0.264000,193.766100,733.962500,2014,60.953172,44715.806369,732.00,0.00,734.00,729.01
6,7,1053615,2014-01-01 00:07:00,734.00,734.34,734.00,734.34,4.000000,2937.306432,734.326608,2014,64.953172,47653.112801,732.00,0.00,734.34,729.01
7,8,1053616,2014-01-01 00:08:00,732.19,733.70,730.33,733.70,13.010490,9508.721435,730.850370,2014,77.963662,57161.834235,732.00,0.00,734.34,729.01
8,10,1053618,2014-01-01 00:10:00,733.70,733.70,733.70,733.70,0.003000,2.201100,733.700000,2014,77.966662,57164.035335,732.00,0.00,734.34,729.01
9,11,1053619,2014-01-01 00:11:00,733.71,733.71,733.70,733.70,2.881830,2114.398765,733.700033,2014,80.848492,59278.434100,732.00,0.00,734.34,729.01
10,12,1053620,2014-01-01 00:12:00,734.00,734.48,734.00,734.48,1.470000,1079.527131,734.372198,2014,82.318492,60357.961231,732.00,0.00,734.48,729.01
11,13,1053621,2014-01-01 00:13:00,734.36,734.50,734.36,734.50,3.122200,2293.188471,734.478403,2014,85.440692,62651.149702,732.00,0.00,734.50,729.01
12,14,1053622,2014-01-01 00:14:00,734.50,734.50,733.70,734.50,12.965575,9521.289692,734.351546,2014,98.406266,72172.439394,732.00,0.00,734.50,729.01
13,15,1053623,2014-01-01 00:15:00,734.50,735.00,734.50,735.00,1.897141,1393.522932,734.538339,2014,100.303408,73565.962326,732.00,0.00,735.00,729.01
14,16,1053624,2014-01-01 00:16:00,734.99,735.00,734.99,735.00,25.472449,18722.216931,734.998702,2014,125.775857,92288.179257,732.00,0.00,735.00,729.01
15,17,1053625,2014-01-01 00:17:00,735.00,735.00,735.00,735.00,1.056800,776.748000,735.000000,2014,126.832657,93064.927257,732.00,0.00,735.00,729.01
16,18,1053626,2014-01-01 00:18:00,732.19,735.00,732.19,735.00,5.050000,3710.972143,734.845969,2014,131.882657,96775.899399,732.00,0.00,735.00,729.01
17,19,1053627,2014-01-01 00:19:00,732.19,732.19,732.19,732.19,0.999700,731.970343,732.190000,2014,132.882357,97507.869742,732.00,0.00,735.00,729.01
18,20,1053628,2014-01-01 00:20:00,732.19,735.48,732.07,735.12,0.191056,140.309389,734.388810,2014,133.073413,97648.179131,732.00,0.00,735.48,729.01
19,21,1053629,2014-01-01 00:21:00,735.48,735.49,731.81,735.49,1.192060,872.991280,732.338372,2014,134.265473,98521.170411,732.00,0.00,735.49,729.01
20,23,1053631,2014-01-01 00:23:00,732.55,732.55,732.03,732.03,0.990000,724.746020,732.066687,2014,135.255473,99245.916431,732.00,0.00,735.49,729.01
21,24,1053632,2014-01-01 00:24:00,732.05,738.00,731.82,731.99,125.161012,92270.936643,737.217884,2014,260.416485,191516.853074,732.00,0.00,738.00,729.01
22,25,1053633,2014-01-01 00:25:00,738.10,738.25,738.10,738.25,4.220000,3115.309214,738.224932,2014,264.636485,194632.162288,732.00,0.00,738.25,729.01
23,27,1053635,2014-01-01 00:27:00,737.66,737.66,734.56,734.56,1.517070,1116.049982,735.661494,2014,266.153555,195748.212271,732.00,0.00,738.25,729.01
24,29,1053637,2014-01-01 00:29:00,734.81,734.81,734.81,734.81,0.026000,19.105060,734.810000,2014,266.179555,195767.317331,732.00,0.00,738.25,729.01
25,32,1053640,2014-01-01 00:32:00,734.81,734.81,734.81,734.81,0.024700,18.149961,734.810000,2014,266.204255,195785.467292,732.00,0.00,738.25,729.01
26,33,1053641,2014-01-01 00:33:00,737.66,738.23,737.66,738.23,2.600000,1919.062390,738.100919,2014,268.804255,197704.529682,732.00,0.00,738.25,729.01
27,34,1053642,2014-01-01 00:34:00,737.66,738.23,737.66,738.23,3.770000,2783.108229,738.224994,2014,272.574255,200487.637911,732.00,0.00,738.25,729.01
28,36,1053644,2014-01-01 00:36:00,735.51,738.23,735.51,738.23,3.122260,2304.806612,738.185317,2014,275.696515,202792.444523,732.00,0.00,738.25,729.01
29,37,1053645,2014-01-01 00:37:00,738.22,738.23,734.81,734.81,13.543910,9970.030348,736.126447,2014,289.240425,212762.474871,732.00,0.00,738.25,729.01
30,38,1053646,2014-01-01 00:38:00,737.75,738.23,737.75,738.23,1.200000,885.837539,738.197949,2014,290.440425,213648.312409,732.00,0.00,738.25,729.01
31,40,1053648,2014-01-01 00:40:00,737.66,737.91,737.66,737.91,2.155986,1590.915733,737.906173,2014,292.596412,215239.228143,732.00,0.00,738.25,729.01
32,41,1053649,2014-01-01 00:41:00,735.47,735.47,735.47,735.47,0.137917,101.433632,735.470000,2014,292.734328,215340.661775,732.00,0.00,738.25,729.01
33,42,1053650,2014-01-01 00:42:00,735.47,738.28,735.47,738.28,42.360000,31268.097592,738.151501,2014,335.094328,246608.759367,732.00,0.00,738.28,729.01
34,43,1053651,2014-01-01 00:43:00,738.28,738.28,735.47,735.47,7.290326,5382.288321,738.278104,2014,342.384655,251991.047688,732.00,0.00,738.28,729.01
35,44,1053652,2014-01-01 00:44:00,735.47,735.47,735.47,735.47,0.009325,6.858111,735.470000,2014,342.393980,251997.905798,732.00,0.00,738.28,729.01
36,45,1053653,2014-01-01 00:45:00,735.47,735.47,735.47,735.47,0.008719,6.412416,735.470000,2014,342.402698,252004.318214,732.00,0.00,738.28,729.01
37,46,1053654,2014-01-01 00:46:00,735.47,738.49,735.47,738.49,5.205402,3844.108227,738.484339,2014,347.608101,255848.426441,732.00,0.00,738.49,729.01
38,47,1053655,2014-01-01 00:47:00,738.31,738.49,734.47,734.47,1.013608,748.481617,738.432678,2014,348.621709,256596.908058,732.00,0.00,738.49,729.01
39,48,1053656,2014-01-01 00:48:00,735.47,738.20,734.50,738.20,3.824190,2820.748737,737.606886,2014,352.445899,259417.656795,732.00,0.00,738.49,729.01
40,49,1053657,2014-01-01 00:49:00,738.19,739.00,734.53,739.00,167.145990,123505.029950,738.905133,2014,519.591889,382922.686745,732.00,0.00,739.00,729.01
41,50,1053658,2014-01-01 00:50:00,739.00,739.00,734.81,739.00,27.580649,20381.887296,738.992303,2014,547.172538,403304.574041,732.00,0.00,739.00,729.01
42,51,1053659,2014-01-01 00:51:00,736.04,739.18,736.04,736.04,4.838370,3575.531972,738.995152,2014,552.010908,406880.106013,732.00,0.00,739.18,729.01
43,52,1053660,2014-01-01 00:52:00,736.13,736.13,736.04,736.04,0.040000,29.444570,736.114250,2014,552.050908,406909.550583,732.00,0.00,739.18,729.01
44,53,1053661,2014-01-01 00:53:00,738.98,739.27,736.04,737.64,5.831960,4311.129566,739.224817,2014,557.882868,411220.680149,732.00,0.00,739.27,729.01
45,54,1053662,2014-01-01 00:54:00,738.98,739.27,737.64,737.64,0.101088,74.651182,738.474044,2014,557.983957,411295.331331,732.00,0.00,739.27,729.01
46,55,1053663,2014-01-01 00:55:00,737.64,739.28,737.64,737.64,4.548020,3360.617897,738.918856,2014,562.531977,414655.949228,732.00,0.00,739.28,729.01
47,56,1053664,2014-01-01 00:56:00,737.64,739.28,737.64,739.28,1.020000,754.000000,739.215686,2014,563.551977,415409.949228,732.00,0.00,739.28,729.01
48,57,1053665,2014-01-01 00:57:00,738.11,738.11,737.64,737.64,0.084049,62.013488,737.824535,2014,563.636026,415471.962716,732.00,0.00,739.28,729.01
49,58,1053666,2014-01-01 00:58:00,738.11,739.90,737.64,737.70,11.422030,8443.702065,739.247057,2014,575.058056,423915.664781,732.00,0.00,739.90,729.01
50,59,1053667,2014-01-01 00:59:00,739.02,739.02,739.02,739.02,0.089524,66.159997,739.020000,2014,0.089524,66.159997,732.00,739.02,739.90,729.01
51,60,1053668,2014-01-01 01:00:00,739.02,739.97,739.02,739.97,14.949450,11059.256836,739.776837,2014,15.038974,11125.416833,739.02,739.02,739.97,739.02
52,62,1053670,2014-01-01 01:02:00,739.00,739.00,739.00,739.00,0.380000,280.820000,739.000000,2014,15.418974,11406.236833,739.02,739.02,739.97,739.00
53,64,1053672,2014-01-01 01:04:00,739.00,739.00,738.11,738.11,0.903966,667.230170,738.113905,2014,16.322940,12073.467003,739.02,739.02,739.97,738.11
54,65,1053673,2014-01-01 01:05:00,738.50,738.50,738.50,738.50,0.100000,73.850000,738.500000,2014,16.422940,12147.317003,739.02,739.02,739.97,738.11

In [232]:
df.drop('level_0', inplace=True, axis=1)
df.drop('index', inplace=True, axis=1)
df.drop('Open', inplace=True, axis=1)
df.drop('Close', inplace=True, axis=1)
df.drop('High', inplace=True, axis=1)
df.drop('Low', inplace=True, axis=1)
df.drop('Volume_(BTC)', inplace=True, axis=1)
df.drop('Volume_(Currency)', inplace=True, axis=1)
df.drop('Weighted_Price', inplace=True, axis=1)
df.drop('Year', inplace=True, axis=1)

In [233]:
df.head()

,Timestamp,BTC_Volume,CURRENCY_Volume,Hourly_Open,Hourly_Close,Hourly_High,Hourly_Low
0,2014-01-01 00:00:00,4.599562,3366.879047,732.0,0.0,732.00,732.00
1,2014-01-01 00:02:00,5.738092,4197.317109,732.0,0.0,732.75,729.01
2,2014-01-01 00:03:00,5.859092,4285.913733,732.0,0.0,732.76,729.01
3,2014-01-01 00:04:00,57.979092,42537.749935,732.0,0.0,734.00,729.01
4,2014-01-01 00:05:00,60.689172,44522.040269,732.0,0.0,734.00,729.01

In [237]:
df['Timestamp']= df['Timestamp'].astype(str)
df2=df.loc[df['Timestamp'].str[-5:] == '59:00']
df2.to_csv('2.csv', sep='\t', encoding='utf-8')